global:
  threadmodel:
    fiber:
      - instance_name: fiber_instance

client:
  service:
    - name: mysql_server
      protocol: mysql
      timeout: 4000
      target: 127.0.0.1:3306
      selector_name: direct
      max_conn_num: 16
      idle_time: 40000

      mysql:
        user_name: "root"
        password: "abc123"
        dbname: "test"
        char_set: "utf8mb4"
        num_shard_group: 4
        thread_num: 4
        thread_bind_core: false


plugins:
  log:
    default:
      - name: default
        sinks:
          local_file:
            filename: trpc_fiber_client.log
